version: '{build}'

platform:
  - x86
#  - x64

branches:
  only:
    - basic_101
    - basic_102
    - basic_142

configuration:
  - Debug
#  - Release

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

before_build:
  - cmake --version

build_script:
  - echo "project basic_101 ......................."
  - git checkout basic_101
  - cmake -GNinja -H. -B_build
  - cmake --build _build
  - ninja -C _build
  - .\bin\main.exe
  - echo "project basic_102 ......................."
  - git checkout basic_102
  - cmake -GNinja -H. -B_build
  - cmake --build _build
  - ninja -C _build
  - .\bin\main.exe
  - echo "project basic_142 ......................."
  - git checkout basic_142
  - cmake -GNinja -H. -B_build
  - ninja -C _build/ get_linuxdeploy
  - cmake --build _build
  - ninja -C _build
  - .\_bin\main_142.exe
  - echo ""
