version: '0.1.{build}'

platform:
  - x86
#  - x64

build:
  parallel: true
  #verbosity: normal

branches:
  only:
    - basic_142

configuration:
  - Debug
  - Release

image: Ubuntu2004

environment:
  matrix:
    #- OS_DISTTAG: ubuntu-18.04
    - OS_DISTTAG: ubuntu-20.04

install:
  - sudo apt-get update
  - sudo apt-get install wget appstream-util appstream apt-config-icons

before_build:
  - cmake --version

build_script:
  - cmake -GNinja -H. -B_build
  - cmake -DCMAKE_BUILD_TYPE=Debug _build
  - ninja -C _build/ get_linuxdeploy
  - cmake --build _build
  - ninja -C _build
  - ./_bin/main_142
  - ninja -C _build install_app
  - ninja -C _build package
  - ./_app/main_142-0.1.0-x86_64.AppImage