version: '{build}'

platform:
  - x86
#  - x64

branches:
  only:
    - basic_101

configuration:
  - Debug
#  - Release

before_build:
  - cmake --version
  - git checkout basic_101
  - cmake -GNinja -H. -Bbuild

build_script:
  - cmake --build build