version: '0.1.{build}'

platform:
  - x86
#  - x64

# build with MSBuild
# build:
  #parallel: true
  #verbosity: normal

branches:
  only:
    - basic_142
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

configuration:
  #- Debug
  - Release

image: Ubuntu2004

environment:
  my_variable:
    secure: 7PAadWhv0Xoxt7rz4NeSWaaSVEtPW0R01ZlHJ7Rqn8QEVKs4i0aBcjWtn7JiN7+X
  matrix:
    - prepare_mode: YES
    #- OS_DISTTAG: ubuntu-18.04
    - OS_DISTTAG: ubuntu-20.04

install:
  - sudo apt-get update
  - sudo apt-get install wget appstream-util appstream apt-config-icons
  - export DISPLAY=:99.0 && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get install p7zip-full
  - wget https://github.com/d1vanov/ciuploadtool/releases/download/continuous-master/ciuploadtool_linux.zip
  - unzip ciuploadtool_linux.zip
  - chmod 755 ciuploadtool

before_build:
  - cmake --version
  - echo $CONFIGURATION

build_script:
  - ./ciuploadtool -suffix="$APPVEYOR_REPO_BRANCH" -preponly
  - cmake -GNinja -H. -B_build -DCMAKE_BUILD_TYPE=$CONFIGURATION
  - ninja -C _build/ get_linuxdeploy
  - cmake --build _build
  - ninja -C _build
  - ./_bin/main_142
  - ninja -C _build install_app
  - ninja -C _build package
  - ./_app/main_142-0.1.0-x86_64.AppImage

after_build:
  #- cd $APPVEYOR_BUILD_FOLDER/_AppDir
  - export DEPLOYMENT_TARGET=basic_142_linux_${APPVEYOR_REPO_COMMIT:0:7}.zip
  - 7z a $DEPLOYMENT_TARGET $APPVEYOR_BUILD_FOLDER/_AppDir/*
  - cmake -E make_directory $APPVEYOR_BUILD_FOLDER/artifacts
  - cp $DEPLOYMENT_TARGET $APPVEYOR_BUILD_FOLDER/artifacts

artifacts:
  - path: 'artifacts/*.zip'
    name: archive

on_finish:
  - echo "APPVEYOR_REPO_BRANCH = $APPVEYOR_REPO_BRANCH"
  - echo "APPVEYOR_BUILD_FOLDER = $APPVEYOR_BUILD_FOLDER"
  - ./ciuploadtool -verbose -suffix="$APPVEYOR_REPO_BRANCH" $APPVEYOR_BUILD_FOLDER/artifacts/$DEPLOYMENT_TARGET

matrix:
  fast_finish: true
  allow_failures:
    - prepare_mode: YES