version: '{build}'

platform:
  - x86
#  - x64

branches:
  only:
    - basic_101
    - basic_102

configuration:
  - Debug
#  - Release

before_build:
  - cmake --version

build_script:
  - git checkout basic_101
  - cmake -GNinja -H. -B_build
  - cmake --build _build
  - git checkout basic_102
  - cmake -GNinja -H. -B_build
  - cmake --build _build