version: '0.1.{build}'

platform:
  - x86
#  - x64

build:
  parallel: true
  #verbosity: normal

branches:
  only:
    - basic_101
    - basic_102
    - basic_142

configuration:
  - Debug
#  - Release

image: Ubuntu2004

environment:
  matrix:
    #- OS_DISTTAG: ubuntu-18.04
    - OS_DISTTAG: ubuntu-20.04

install:
  - sudo apt-get update
  - sudo apt-get install wget appstream-util appstream apt-config-icons

before_build:
  - cmake --version

build_script:
  - echo "project basic_101 ......................."
  - git checkout basic_101
  - cmake -GNinja -H. -B_build
  - cmake --build _build
  - ninja -C _build
  - ./bin/main
  - echo "project basic_102 ......................."
  - git checkout basic_102
  - cmake -GNinja -H. -B_build
  - cmake --build _build
  - ninja -C _build
  - ./bin/main