version: '{build}'

platform:
  - x86
#  - x64

branches:
  only:
    - basic_101
    - basic_102
    - basic_142

configuration:
  - Debug
#  - Release

image: Ubuntu2004

environment:
  matrix:
    - OS_DISTTAG: ubuntu-20.04

install:
  - sh: |
    echo "I am the install script for OS_DISTTAG=${OS_DISTTAG}"
  - sh: sudo ln -s /usr/bin/clang-9.0 /usr/bin/clang
  - sh: sudo ln -s /usr/bin/clang++-9.0 /usr/bin/clang++

before_build:
  - cmake --version
  - clang-9 .0 --version

build_script:
  - echo "project basic_101 ......................."
  - git checkout basic_101
  - cmake -GNinja -H. -B_build
  - cmake --build _build
  - ninja -C _build
  - .\bin\main.exe
  - echo "project basic_102 ......................."
  - git checkout basic_102
  - cmake -GNinja -H. -B_build
  - cmake --build _build
  - ninja -C _build
  - .\bin\main.exe
  - echo "project basic_142 ......................."
  - git checkout basic_142
  - cmake -GNinja -H. -B_build
  #- ninja -C _build/ get_linuxdeploy
  - cmake --build _build
  - ninja -C _build
  - .\_bin\main_142.exe
  - echo ""
